// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

#ifndef PROTOBUF_Common_2eproto__INCLUDED
#define PROTOBUF_Common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Common_2eproto();
void protobuf_AssignDesc_Common_2eproto();
void protobuf_ShutdownFile_Common_2eproto();

class Common;

// ===================================================================

class Common : public ::google::protobuf::Message {
 public:
  Common();
  virtual ~Common();
  
  Common(const Common& from);
  
  inline Common& operator=(const Common& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Common& default_instance();
  
  void Swap(Common* other);
  
  // implements Message ----------------------------------------------
  
  Common* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Common& from);
  void MergeFrom(const Common& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string TypeName = 1 [default = ""];
  inline bool has_typename_() const;
  inline void clear_typename_();
  static const int kTypeNameFieldNumber = 1;
  inline const ::std::string& typename_() const;
  inline void set_typename_(const ::std::string& value);
  inline void set_typename_(const char* value);
  inline void set_typename_(const char* value, size_t size);
  inline ::std::string* mutable_typename_();
  inline ::std::string* release_typename_();
  
  // @@protoc_insertion_point(class_scope:Common)
 private:
  inline void set_has_typename_();
  inline void clear_has_typename_();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* typename__;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_Common_2eproto();
  friend void protobuf_AssignDesc_Common_2eproto();
  friend void protobuf_ShutdownFile_Common_2eproto();
  
  void InitAsDefaultInstance();
  static Common* default_instance_;
};
// ===================================================================


// ===================================================================

// Common

// required string TypeName = 1 [default = ""];
inline bool Common::has_typename_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Common::set_has_typename_() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Common::clear_has_typename_() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Common::clear_typename_() {
  if (typename__ != &::google::protobuf::internal::kEmptyString) {
    typename__->clear();
  }
  clear_has_typename_();
}
inline const ::std::string& Common::typename_() const {
  return *typename__;
}
inline void Common::set_typename_(const ::std::string& value) {
  set_has_typename_();
  if (typename__ == &::google::protobuf::internal::kEmptyString) {
    typename__ = new ::std::string;
  }
  typename__->assign(value);
}
inline void Common::set_typename_(const char* value) {
  set_has_typename_();
  if (typename__ == &::google::protobuf::internal::kEmptyString) {
    typename__ = new ::std::string;
  }
  typename__->assign(value);
}
inline void Common::set_typename_(const char* value, size_t size) {
  set_has_typename_();
  if (typename__ == &::google::protobuf::internal::kEmptyString) {
    typename__ = new ::std::string;
  }
  typename__->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Common::mutable_typename_() {
  set_has_typename_();
  if (typename__ == &::google::protobuf::internal::kEmptyString) {
    typename__ = new ::std::string;
  }
  return typename__;
}
inline ::std::string* Common::release_typename_() {
  clear_has_typename_();
  if (typename__ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = typename__;
    typename__ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Common_2eproto__INCLUDED
