/* soapClient.cpp
   Generated by gSOAP 2.8.14 from WebServiceDeclare.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.14 2013-02-27 06:45:02 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__paynotify(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *szAccount, int nKindID, int nServerID, int &nRes)
{	struct ns__paynotify soap_tmp_ns__paynotify;
	struct ns__paynotifyResponse *soap_tmp_ns__paynotifyResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://xaobama.eicp.net:10010/";
	soap->encodingStyle = "";
	soap_tmp_ns__paynotify.szAccount = szAccount;
	soap_tmp_ns__paynotify.nKindID = nKindID;
	soap_tmp_ns__paynotify.nServerID = nServerID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__paynotify(soap, &soap_tmp_ns__paynotify);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__paynotify(soap, &soap_tmp_ns__paynotify, "ns:paynotify", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__paynotify(soap, &soap_tmp_ns__paynotify, "ns:paynotify", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&nRes)
		return soap_closesock(soap);
	soap_default_int(soap, &nRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__paynotifyResponse = soap_get_ns__paynotifyResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	nRes = soap_tmp_ns__paynotifyResponse->nRes;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
